# Generated by Django 2.0.2 on 2018-02-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='name',
            field=models.CharField(default='lion', max_length=8),
        ),
        migrations.AddField(
            model_name='animal',
            name='sound',
            field=models.CharField(default='roar', max_length=8),
        ),
    ]
